/**
 * HTML Template for standalone mindmap files
 *
 * Requirements:
 * - 14.2: Generate HTML with all necessary CSS and JavaScript inlined
 *
 * This template provides the base HTML structure with:
 * - Proper meta tags for charset and viewport
 * - CSS placeholder for inlined styles
 * - JS placeholder for inlined scripts
 * - Dark mode support
 * - Responsive design
 */

export interface TemplateOptions {
  title: string;
  theme: 'light' | 'dark';
}

/**
 * Generate the base HTML template
 *
 * @param options - Template options
 * @returns HTML template string with placeholders
 */
export function generateTemplate(options: TemplateOptions): string {
  const { title, theme } = options;
  const darkClass = theme === 'dark' ? ' class="markmap-dark"' : '';

  return `<!DOCTYPE html>
<html lang="zh-CN"${darkClass}>
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <meta name="theme-color" content="${theme === 'dark' ? '#1a1a2e' : '#ffffff'}">
  <meta name="description" content="Interactive mindmap generated by Markmap">
  <title>${escapeHtml(title)}</title>
  <!--STYLES-->
</head>
<body>
  <svg id="mindmap"></svg>
  <div id="toolbar-container"></div>
  <!--SCRIPTS-->
</body>
</html>`;
}

/**
 * Escape HTML special characters to prevent XSS
 *
 * @param text - Text to escape
 * @returns Escaped text
 */
function escapeHtml(text: string): string {
  const htmlEscapes: Record<string, string> = {
    '&': '&amp;',
    '<': '&lt;',
    '>': '&gt;',
    '"': '&quot;',
    "'": '&#39;',
  };
  return text.replace(/[&<>"']/g, (char) => htmlEscapes[char] || char);
}

/**
 * Base CSS styles for the mindmap container
 * These styles ensure proper full-screen display and basic theming
 */
export const BASE_STYLES = `
/* Base Reset and Layout */
* {
  margin: 0;
  padding: 0;
  box-sizing: border-box;
}

html, body {
  width: 100%;
  height: 100%;
  overflow: hidden;
  font-family: ui-sans-serif, system-ui, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';
}

#mindmap {
  display: block;
  width: 100vw;
  height: 100vh;
}

/* Dark mode support */
.markmap-dark {
  background: #1a1a2e;
  color: #e0e0e0;
}

.markmap-dark #mindmap {
  background: #1a1a2e;
}

/* Toolbar container positioning */
#toolbar-container {
  position: fixed;
  top: 0;
  left: 0;
  right: 0;
  z-index: 1000;
  pointer-events: none;
}

#toolbar-container > * {
  pointer-events: auto;
}
`;
